### PR TITLE
Fix CN length limitation issue while using cert-manager

### LINKED ISSUE #445: Controller certificate CN too long
**Describe the bug**
Kafka clusters with medium sized names in namespaces with medium sized names fail to create, with an error like the following in the logs:

```
{"level":"error","ts":1599151167.7324488,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"kafkauser","request":"pushdelivery-stage/kafka-pushdelivery-stage-controller.pushdelivery-stage.mgt.cluster.local","error":"could not create user certificate: admission webhook \"webhook.cert-manager.io\" denied the request: spec.commonName: Too long: must have at most 64 bytes","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}
```

**Steps to reproduce the issue:**
Create a Kafka cluster in a namespace whose effective commonName is longer than 64 characters

**Additional context**
I ran into this error rebuilding my cluster after https://github.com/banzaicloud/kafka-operator/issues/444 happened. Weirdly, this was successful before, and in production I have an even longer name ("production" vs "stage") that is running just fine. Even though I have the same versions of cert-manager and kafka-operator in both environments, the stage environment has been upgraded to Kubernetes 1.16, while production is still on 1.15. 

I found a workaround for this, which was to disable the admission webhook for cert-manager. I think I created these clusters (and their certs) before the webhook was in play, which is why production is still working - the resource was already admitted before the validation was added.

### PR DESCRIPTION
**Pull request by panyuenlau**
| Q               | A      |
| --------------- | ------ |
| Bug fix?        | yes |
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets | fixes #445|
| License         | Apache 2.0 |

### What's in this PR?

Hash and limit the length of the generated CN for the controller if it exceeds the maximum supported length - 64 characters, reference:  https://docs.digicert.com/manage-certificates/public-certificates-data-entries-that/#64character-maximum-limit-violation

### Additional context

Tested with cert-manager (as well as csr-operator) using the same Kafka name and namespace as reported in #445 

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)

### TODO
- [x] Fix following error when SSL is enabled: 
`{"level":"info","ts":"2022-06-15T05:01:57.596Z","logger":"controller.KafkaCluster","msg":"A new resource was not found or may not be ready","reconciler group":"kafka.banzaicloud.io","reconciler kind":"KafkaCluster","name":"kafka-pushdelivery-stage-controller","namespace":"pushdelivery-stage","error":"checking secret data fields: SSL JKS certificate has not generated properly yet into secret: kafka-pushdelivery-stage-controller-server-certificate"}
`

### CODE REVIEW

File: pkg/util/pki/common.go [hunk 1]
```diff
@@ -243,3 +245,12 @@ func EnsureControllerReference(ctx context.Context, user *v1alpha1.KafkaUser,
 	}
 	return nil
 }
+
+// TruncatedCommonName ensures that the passed-in common name doesn't exceed the specified number of characters
+func TruncatedCommonName(name string, maxLen int) string {
```
Comment (hi-im-aren) [inline pkg/util/pki/common.go:250]: We could use `TruncateCommonName` instead so it's a verb as a function name?
Maybe we could move this to a common/util package and make it a generic string truncate function.

**Review by pregnor — APPROVED** [review]

File: pkg/util/pki/common.go [hunk 2]
```diff
@@ -57,6 +58,8 @@ const (
 	// KafkaUserAnnotationName used in case of PKIbackend is k8s-csr to find the appropriate kafkauser in case of
 	// signing request event
 	KafkaUserAnnotationName = "banzaicloud.io/owner"
+	// MaxCertManagerCNLen specifies the maximum common name supported by cert-manager
+	MaxCertManagerCNLen = 64
```
Comment (stoader) [inline pkg/util/pki/common.go:62]: The max length limit on CN field I think is rather imposed by certificate standards and not cert-manager this comment should be updated accordingly (see https://docs.digicert.com/manage-certificates/public-certificates-data-entries-that/#64character-maximum-limit-violation)

File: pkg/util/pki/common.go [hunk 3]
```diff
@@ -215,9 +218,9 @@ func sortAndDedupe(hosts []string) []string {
 func ControllerUserForCluster(cluster *v1beta1.KafkaCluster) *v1alpha1.KafkaUser {
 	return &v1alpha1.KafkaUser{
 		ObjectMeta: templates.ObjectMeta(
-			fmt.Sprintf(BrokerControllerFQDNTemplate,
-				fmt.Sprintf(BrokerControllerTemplate, cluster.Name), cluster.Namespace, cluster.Spec.GetKubernetesClusterDomain()),
-			LabelsForKafkaPKI(cluster.Name, cluster.Namespace), cluster,
+			util.TruncateStringByLen(fmt.Sprintf(BrokerControllerFQDNTemplate, fmt.Sprintf(BrokerControllerTemplate, cluster.Name), cluster.Namespace, cluster.Spec.GetKubernetesClusterDomain()), MaxCertManagerCNLen),
```
Comment (stoader) [inline pkg/util/pki/common.go:221]: Do we need to truncate the name of the created `KafkaUser` custom resource as well? Or only just the CommonName field in the created `Certificate` resource? I'm asking as for K8s resource names different rules apply (see https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names)

File: pkg/util/util.go [hunk 4]
```diff
@@ -451,3 +451,12 @@ func ObjectManagedByClusterRegistry(object metav1.Object) bool {
 	_, ok := annotations[clusterregv1alpha1.OwnershipAnnotation]
 	return ok
 }
+
+// TruncatedCommonName ensures that the passed-in common name doesn't exceed the specified number of characters
+func TruncateStringByLen(name string, l int) string {
```
Comment (stoader) [inline pkg/util/util.go:456]: Is it enough just to simply truncate the common name or we have to ensure that it stays unique after truncation? Eg two different KafkaUsers should be represented by two different certificates.

If uniqueness needs to be ensured than a has code could be be computed from the original value and appended to the truncated value.

**Review by stoader — CHANGES_REQUESTED** [review]

File: pkg/util/pki/common.go (hunk 3 above)
Comment (panyuenlau) [reply pkg/util/pki/common.go:221]: We need to ensure the `name` field of the generated `KafkaUser` doesn't exceed the length limitation as well because the [`clusterCertificateForUser`](https://github.com/banzaicloud/koperator/blob/master/pkg/pki/certmanagerpki/certmanager_user.go#L146) function uses it as the `spec.commonName` while generating a `Certificate` object for the corresponding `KafkaUser`

In fact, it is the first error reported by the operator when our user reported this issue in #445

File: pkg/util/util.go (hunk 4 above)
Comment (panyuenlau) [reply pkg/util/util.go:456]: I thought about hashing the entire string and limiting it to 64 chars as well, but I realized it could be difficult for the users to debug if things go wrong since the hashed string is un-comprehensible.

In terms of uniqueness, since the common name is constructed with `cluster.Name` and`cluster.Namespace`, I thought this is enough to ensure the uniqueness of the entire string since we cant't have the same kafka cluster name under the same namespace

File: pkg/util/pki/common.go (hunk 2 above)
Comment (panyuenlau) [reply pkg/util/pki/common.go:62]: will update the var and comment to reflect this

File: pkg/util/pki/common.go (hunk 3 above)
Comment (stoader) [reply pkg/util/pki/common.go:221]: In `clusterCertificateForUser` you could just perform the truncation just before passing it into `spec.commonName`

**Review by pregnor — DISMISSED** [review]

File: pkg/util/pki/pki_common_test.go [hunk 5]
```diff
@@ -175,3 +175,42 @@ func TestControllerUserForCluster(t *testing.T) {
...
+	testCases := []struct {
+		testName             string
+		commonName           string
+		expectedHashedString string
+		expectedLen          int
+	}{
+		{
+			testName:    "Common name with length exceeded limitation",
+			commonName:  "kafka-test-controller-exceeded-length.test-namespace.mgt.cluster.local",
+			expectedLen: MaxCNLen,
```
Comment (stoader) [inline pkg/util/pki/pki_common_test.go:189]: beside the lenght also the expected output could be verified as well.

Comment (panyuenlau) [reply pkg/util/pki/pki_common_test.go:189]: yea...but we since don't actually care about the content of the hashed string, I don't see the necessity of verifying it in the test

**Review by stoader — DISMISSED** [review]

**Review by Kuvesz — APPROVED** [review]

**Review by stoader — APPROVED** [review]

**Review by pregnor — APPROVED** [review]
