### PR TITLE
Use the number of distinct brokers with offline partition or out of sync replicas as error count during rolling upgrade

### LINKED ISSUE #695: Rolling upgrade failureThreshold not working as intended above the default value 1
**Describe the bug**
The current form of failureThreshold would have the same effect  any value above 1 (ex. there is no difference between failureThreshold value of 2 or 3). Furthermore, the errorCount, against which the failureThreshold is compared to, is always reseted to 0 and never written back to the status.

**Expected behavior**
Failure threshold is stating how many errors can the cluster tolerate during a rolling upgrade (ex. if guarding for a broker failure during a rolling upgrade).

### PR DESCRIPTION
**Pull request by stoader**
| Q               | A      |
| --------------- | ------ |
| Bug fix?        | yes |
| New feature?    | yes |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets | fixes #695 |
| License         | Apache 2.0 |

### What's in this PR?

The number of failures during a rolling upgrade is is computed as the sum of distinct broker replicas with either offline replicas or out of sync replicas and the number of alerts triggered by alerts with 'rollingupgrade'

### Why?

The current implementation doesn't honor failureThreshold that is greater than 1, only when there is a 'rollingupgrade' alert firing that increases the error count during rolling upgrade.

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] User guide and development docs updated (if needed)

### CODE REVIEW

File: api/v1beta1/kafkacluster_types.go [hunk 1]
```diff
@@ -97,11 +97,17 @@ type KafkaClusterStatus struct {
...
 	LastSuccess string `json:"lastSuccess"`
-	ErrorCount  int    `json:"errorCount"`
+	// ErrorCount keeps track the number of errors reported by alerts labeled with 'rollingupgrade'.
+	// It's reset once these alerts stop firing.
+	ErrorCount int `json:"errorCount"`
 }
 
 // RollingUpgradeConfig defines the desired config of the RollingUpgrade
 type RollingUpgradeConfig struct {
+	// FailureThreshold controls how many failures can the cluster tolerate during a rolling upgrade. Once the number of
```
Comment (amberimam) [inline api/v1beta1/kafkacluster_types.go:107]:
```suggestion
	// FailureThreshold controls how many failures the cluster can tolerate during a rolling upgrade. Once the number of
```

File: charts/kafka-operator/templates/crds.yaml [hunk 2]
```diff
@@ -18553,6 +18553,12 @@ spec:
                   RollingUpgrade
                 properties:
                   failureThreshold:
+                    description: FailureThreshold controls how many failures can the
+                      cluster tolerate during a rolling upgrade. Once the number of
```
Comment (amberimam) [inline charts/kafka-operator/templates/crds.yaml:18557]:
```suggestion
                    description: FailureThreshold controls how many failures the
                      cluster can tolerate during a rolling upgrade. Once the number of
```

File: config/base/crds/kafka.banzaicloud.io_kafkaclusters.yaml [hunk 3]
```diff
@@ -18552,6 +18552,12 @@ spec:
                   RollingUpgrade
                 properties:
                   failureThreshold:
+                    description: FailureThreshold controls how many failures can the
+                      cluster tolerate during a rolling upgrade. Once the number of
```
Comment (amberimam) [inline config/base/crds/kafka.banzaicloud.io_kafkaclusters.yaml:18556]:
```suggestion
                    description: FailureThreshold controls how many failures the
                      cluster can tolerate during a rolling upgrade. Once the number of
```

File: config/samples/banzaicloud_v1beta1_kafkacluster.yaml [hunk 4]
```diff
@@ -39,7 +39,10 @@ spec:
   # brokerConfigGroups specifies multiple broker configs with unique name
   #rollingUpgradeConfig specifies the rolling upgrade config for the cluster
   #rollingUpgradeConfig:
-  #failureThreshold states that how many errors can the cluster tolerate during rolling upgrade
+  #failureThreshold controls how many failures can the cluster tolerate during a rolling upgrade. Once the number of
```
Comment (amberimam) [inline config/samples/banzaicloud_v1beta1_kafkacluster.yaml:42]:
```suggestion
  #failureThreshold controls how many failures the cluster can tolerate during a rolling upgrade. Once the number of
```

**Review by amberimam — CHANGES_REQUESTED** [review]
Just a couple of nits.

File: pkg/resources/kafka/kafka.go [hunk 5]
```diff
@@ -663,18 +663,31 @@ func (r *Reconciler) handleRollingUpgrade(log logr.Logger, desiredPod, currentPo
...
-				errorCount++
+			impactedReplicas := make(map[int32]struct{})
+			for _, brokerID := range allOfflineReplicas {
+				impactedReplicas[brokerID] = struct{}{}
+			}
+			for _, brokerID := range outOfSyncReplicas {
+				impactedReplicas[brokerID] = struct{}{}
 			}
+
+			errorCount += len(impactedReplicas)
```
Comment (adamantal) [inline pkg/resources/kafka/kafka.go:689]: Since we're counting the individual failures, shouldn't this value be calculated as:
```
			errorCount = len(impactedReplicas)
```

Otherwise how do you make sure you doesn't count the same replica failure twice?

**Review by adamantal — COMMENTED** [review]
LGTM. One question on the calculation of errors.

File: pkg/resources/kafka/kafka.go (hunk 5 above)
Comment (stoader) [reply pkg/resources/kafka/kafka.go:689]: `errorCount` is initialised with the value from `r.KafkaCluster.Status.RollingUpgrade.ErrorCount` (the error count set by rollingupgrade alerts) that we need to add `len(impactedReplicas)` to the initial value.

**Review by baluchicken — APPROVED** [review]
LGTM thx @stoader

File: pkg/resources/kafka/kafka.go (hunk 5 above)
Comment (adamantal) [reply pkg/resources/kafka/kafka.go:689]: Discussed offline. The ErrorCount stems from Prometheus, we just add our own counter there. Thanks for the clarification.

**Review by adamantal — APPROVED** [review]
Thanks for resolving this issue!

**Review by hi-im-aren — APPROVED** [review]

**Review by amberimam — APPROVED** [review]
Looks good!
