### PR TITLE
Delete old kafka service when headlessServiceEnabled changed

### LINKED ISSUE #532: svc was not Delete
**Describe the bug**
`headlessServiceEnabled` initially is true, Then I  set `headlessServiceEnabled: false`, and found that the same number of `svc` as the broker was created, which was in line with expectations, but when I changed to `headlessServiceEnabled: true`, the corresponding `svc` was not Delete.

**Steps to reproduce the issue:**
Please describe the steps to reproduce the issue.
- 1、set `headlessServiceEnabled：true `, apply YAML file.
- 2、set `headlessServiceEnabled：false`, apply YAML file.
- 3、set `headlessServiceEnabled：true `, apply YAML file.

image

**Expected behavior**
  `svc` is deleted.

**Screenshots**

**Additional context**
 version: 0.14.0

### PR DESCRIPTION
**Pull request by stoader**
| Q               | A      |
| --------------- | ------ |
| Bug fix?        | yes |
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets | fixes #532 |
| License         | Apache 2.0 |

### What's in this PR?

Delete old kafka broker service when the `headlessServiceEnabled` is changed. 

### Why?

When `headlessServiceEnabled` is changed new Kubernetes service is created and the old one is not deleted even though is not needed any more.

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline

### CODE REVIEW

**Review by Kuvesz — DISMISSED** [review]
LGTM but would love if someone more experienced took a look at this. :)

File: pkg/resources/kafka/allBrokerService.go [hunk 1]
```diff
@@ -36,15 +45,79 @@ func (r *Reconciler) allBrokerService() runtime.Object {
...
+	)
+
+	if err != nil {
+		return errors.WrapIfWithDetails(err, "failed to list services",
+			"namespace", r.KafkaCluster.GetNamespace(),
+			"label selector", labelSelector.String())
+	}
+
+	for i := range services.Items {
+		svc := services.Items[i]
```
Comment (panyuenlau) [inline pkg/resources/kafka/allBrokerService.go:112]: Since there was an `svc` created at the beginning of the function, maybe we could just overwrite that variable instead of re-creating new ones in the for loop
```suggestion
		svc = services.Items[i]
```

File: pkg/resources/kafka/allBrokerService.go [hunk 2]
```diff
@@ -36,15 +45,79 @@ func (r *Reconciler) allBrokerService() runtime.Object {
...
+		if !svc.GetDeletionTimestamp().IsZero() {
+			continue
+		}
+		err := r.Client.Delete(ctx, &svc)
```
Comment (panyuenlau) [inline pkg/resources/kafka/allBrokerService.go:116]: Same here, we can just overwrite the `err` that was created earlier in the function to save some memory
```suggestion
		err = r.Client.Delete(ctx, &svc)
```

Comment (panyuenlau) [inline pkg/resources/kafka/allBrokerService.go:116]: Same here, we can just overwrite the `err` that was created earlier in the function to save some memory
```suggestion
		err = r.Client.Delete(ctx, &svc)
```

**Review by panyuenlau — DISMISSED** [review]
Just a couple of nits

**Review by panyuenlau — APPROVED** [review]

**Review by pregnor — APPROVED** [review]

**Comment by pregnor** [comment]
Give a thought to [this comment](https://github.com/banzaicloud/koperator/pull/779/files#r857073328) before merging.

> bincherry: I found that cruisecontrol should restart after the service changing, otherwise it will runs into error.

**Comment by stoader** [comment]
`koperator` reconciler processes first the Kafka cluster than the Cruise Control deployment:
https://github.com/banzaicloud/koperator/blob/master/controllers/kafkacluster_controller.go#L120-L121

When CC is reconciled it's config will be updated with the new kafka bootstrap server address: https://github.com/banzaicloud/koperator/blob/master/pkg/resources/cruisecontrol/configmap.go#L54

CC pod will exit with an error as won't be able to connect to the old deleted service, when i's restarted by the pod will pick up the new CC config which has the new Kafka service.

If we want to make CC to pick up the new address without exiting with an error we should rather compute the hash from the config map as that contains both user provided config and generated config.
